# 指定测试项目，分IPTV和OTT
project: OTT

device:
  # 测试设备和包名，用于通过adb获取信息
  id:
  package: com.mgtv.tv
#  id: 192.168.202.125:5555
#  package: com.hunantv.operator

# url中显示上报类型
display: on
# 显示原始数据
primitive: off
# 字段缺失校验
lack: off
# 接口请求参数排序
sort: on


OTT:
  common:
    # 公共字段
    time: time_compare-14
    sessionid: empty_compare
    did: a760a60cace7
    newdid: len_compare-36
    uuid: empty_compare
    net: 1
    isdebug: 0
    mf: HUAWEI
    mod: ALT-AL10
    model: ALT-AL10
    sver: OpenHarmony-5.0.4.155
    aver: 6.2.501.633.3.HWHMSDK_TVSDK.0.0_Debug
    ver: ver_compare
    patchid: empty_compare
    lics: empty_compare
    uvip: uvip_compare
    ot: '1'
    abt: inter_compare
  #  src: 'mgtv'
    caplayer: '1'
  #  paid: inter_compare
    agemod: '0'
    localip: localip_compare
    pver: empty_compare

    # apm上报
    app_version: ver_compare
    channel: 'ott'
    device_id: 'a7:60:a6:0c:ac:e7'
    event_type: 'apm'
    is_vip: uvip_compare
    lib: 'Harmony'
    lib_version: '3.0.9.1.c'
    manufacturer: HUAWEI
    network_type: 'WIFI'
    os: OpenHarmony-5.0.4.155
    os_version: 5.0.4.155
    project: pcdn

  private:
    # 私有字段
    bid: bid_compare
    bsid: inter_compare
    cf: inter_compare
    cid: cid_compare
    cntp: cntp_compare
    cpn: cntp_compare
#    lastp: inter_latest_compare
    fpn: inter_latest_compare
    cpid: cpid_compare
    fpid: inter_latest_compare
    vid: inter_compare
    ovid: inter_compare
    sovid: inter_compare
    plid: inter_compare
    oplid: inter_compare
    soplid: inter_compare
    def: inter_compare
    bdid: inter_compare
    isIntact: inter_compare
    refcdn: '1'
    sct: sct_compare
    purl: inter_compare
    vts: inter_compare
    suuid: suuid_compare
    lob: lob_compare
    pay: pay_compare
    istry: istry_compare
    vipdc: vipdc_compare
    vloc: vloc_compare
    protype: inter_compare
    mclassid: inter_compare
    _domain: domain_compare
    _method: method_compare

  # 忽略字段
  ignore:
    - package
    - osver
    - asid
    - logtype
    - act
    - cpn
    - fpn
    - bdsv
    - _json

  # 字段名不同
  alias:
    clipId:
      - plid
      - oplid
      - soplid
    # 不能与clipId统一，bdid等会错误赋值
    plId:
      - bdid
      - oplid
      - plid
    seriesId:
      - bsid
    videoId:
      - vid
      - ovid
      - sovid
    # 短视频
    topicId:
      - cid
    subTopicId:
      - oplid
      - plid
    partId:
      - vid
      - ovid

    duration:
      - vtsd
    fstlvlId:
      - cid
    guid:
      - sessionid
    isIntact:
      - cf
    os_ver:
      - sver
    quality:
      - def
    version:
      - ver
      - aver
    url:
      - purl
    cntp:
      - cpn
    isVip:
      - uvip
    type:
      - protype
    channelId:
      - mclassid
    mod:
      - model

  #
  fixed:
    appls:
      bid: '3.9.1'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    chottshow:
      bid: '3.1.34'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    click:
      bid: '40.5.5.5'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    cmc:
      bid: '3.1.26'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    cms:
      bid: '3.1.26'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    cp1:
      bid: '3.1.90'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'GET'
    cv:
      bid: '40.2.1'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    error:
      bid: '3.1.3'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    heartbeat:
      bid: '3.1.1'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    hotfix:
      bid: '40.6.1'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    pv:
      bid: '3.1.12'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    play:
      bid: '3.1.1'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    'on':
      bid: '3.1.32'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    recshow:
      bid: '3.1.29'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    scrs:
      bid: '3.1.28'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    splay:
      bid: '3.4.1'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    stay:
      bid: '3.1.13'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    stop:
      bid: '3.1.1'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    w2aframeload:
      bid: '3.1.37'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    w2apageload:
      bid: '3.1.38'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    tvappclick:
      bid: '40.2.23'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    tvappsearch:
      bid: '40.2.23'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    tvappview:
      bid: '40.2.23'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    pause:
      bid: '3.1.35'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    resume:
      bid: '3.1.36'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    buffer:
      bid: '3.1.25'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    drag:
      bid: '3.1.30'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    nettest:
      bid: '3.1.133'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    playtest:
      bid: '3.1.23'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    sdkload:
      bid: '3.1.33'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    dvon:
      bid: '3.1.132'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    play_three_layers:
      _domain: 'dpapm.log.mgtv.com'
      _method: 'POST'
    play_start:
      _domain: 'dpapm.log.mgtv.com'
      _method: 'POST'
    page_load:
      _domain: 'dpapm.log.mgtv.com'
      _method: 'POST'
    app_start:
      _domain: 'dpapm.log.mgtv.com'
      _method: 'POST'
    JIAGU_APP_RESULT:
      _domain: 'dpapm.log.mgtv.com'
      _method: 'POST'
    app_thread_hb:
      _domain: 'dpapm.log.mgtv.com'
      _method: 'POST'
    resp_time:
      _domain: 'dpapm.log.mgtv.com'
      _method: 'POST'
    pic_load_err:
      _domain: 'dpapm.log.mgtv.com'
      _method: 'POST'
    guidedown:
      bid: '3.1.39'
      _domain: 'ott.v1.data.mgtv.com'
      _method: 'POST'
    flow:
      _domain: 'pdata.log.mgtv.com'
      _method: 'POST'
    perf_score:
      _domain: 'pdata.log.mgtv.com'
      _method: 'POST'
